export enum MutationTypes {
  SET_NETWORK_API = 'SET_NETWORK_API',
  SET_INITIALIZED = 'SET_INITIALIZED',
  SET_LOADING = 'SET_LOADING',
  SET_SHOW_ALERT_MSG = 'SET_SHOW_ALERT_MSG',
  SET_ALERT_MSG = 'SET_ALERT_MSG',
  SET_CURRENT_NETWORK_IDX = 'SET_CURRENT_NETWORK_IDX',
  SET_CURRENT_ACCOUNT_IDX = 'SET_CURRENT_ACCOUNT_IDX',
  SET_CURRENT_CUSTOM_ENDPOINT = 'SET_CURRENT_CUSTOM_ENDPOINT',
}
