export enum MutationTypes {
  SET_NETWORK_API = 'SET_NETWORK_API',
  SET_INITIALIZED = 'SET_INITIALIZED',
  SET_CURRENT_NETWORK_IDX = 'SET_CURRENT_NETWORK_IDX',
  SET_CURRENT_ACCOUNT_IDX = 'SET_CURRENT_ACCOUNT_IDX',
}
