name: PR
on: [pull_request]

jobs:
    lint:
        name: Linting
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Yarn
              run: npm install -g yarn
            - name: lint
              run: |
                  yarn install --frozen-lockfile
                  yarn lint

    test:
        name: Testing
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Yarn
              run: npm install -g yarn
            - name: test
              run: |
                  yarn install --frozen-lockfile
                  yarn test

    build_code:
        name: Build Code
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [12.x]
        steps:
            - uses: actions/checkout@v1
              with:
                  token: ${{ secrets.GH_PAT }}
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Yarn
              run: npm install -g yarn
            - name: build
              env:
                  CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
                  GH_PAGES_SRC: build
                  GH_PAT: ${{ secrets.GH_PAT }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  yarn install --frozen-lockfile
                  yarn build
